### ISSUE TITLE
get_issue_list cannot fetch all issues

### ISSUE THREAD

**Issue by tockri** [koxudaxi/BacklogPy#74]
Hi, I'm using BacklogPy for my personal development, thank you for sharing the awesome library!

Let me report a small issue.
When I call `get_issue_list` simply, it returns not all issues but issues without attachment files.

I guess that is because [these codes](https://github.com/koxudaxi/BacklogPy/blob/master/BacklogPy/api/issues.py#L549-L550) accidentally converts `None` to `FALSE`.

Could you plan to fix it?

p.s. If you are too busy to fix it, I'm ready to create a pull request!

※ 日本語で書くべきか英語で書くべきか迷ったのでとりあえず英語にしました。

**Comment by koxudaxi** [comment]
@tockri
I'm sorry for my late reply 🙇 

I have fixed the problem and published a new version `1.1.1` 🎉 

> ※ 日本語で書くべきか英語で書くべきか迷ったのでとりあえず英語にしました。

We should speak in English Because I guess backlog is used in other countries. 
Thank you very much.

**Comment by tockri** [comment]
@koxudaxi Thanks a lot! 👍 👍
